# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo %cd%
  displayName: 'Run first cmd'

- script: |
    echo start of wait
    timeout /T 5
    echo completed wait
    dir
    echo %cd%

- script: |
    echo %cd%
    dir
    echo this is a multi line command
    cd Build.StagingDirectory
    dir
    echo %cd%
    cd Build.StagingDirectory/packages
    dir
    echo %cd%
  displayName: 'Run a multi-line script'

