# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
    

steps:
#     azureSubscription: 'Free Trial (e60e4250-e749-4da3-a098-04df412b24c5)'
- task: Docker@2
  inputs:
    connectionName: AzureTrialSubscr
#    azureSubscription: 'Free Trial (e60e4250-e749-4da3-a098-04df412b24c5)'
    azureContainerRegistry: '{"loginServer":"mycontainerregistryem.azurecr.io", "id" : "myContainerRegistryEM"}'
    repository: 'mycontainerregistryem.azurecr.io/egam1/demo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


