# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  - task: Docker@1
    displayName: 'Build an image'
    inputs:
      azureSubscriptionEndpoint: 'k8-demo - Azure'
      azureContainerRegistry: emmycontainerregistry.azurecr.io
      dockerFile: Dockerfile
      imageName: 'emmycontainerregistry.azurecr.io/k8demo4d75:$(Build.BuildId)'
      useDefaultContext: false

    - task: Docker@2
      displayName: 'Push an image'
      inputs:
        azureSubscriptionEndpoint: 'k8-demo - Azure'
        azureContainerRegistry: emmycontainerregistry.azurecr.io
        command: 'Push an image'
        Dockerfile: '**/Dockerfile'
        imageName: 'emmycontainerregistry.azurecr.io/k8demo4d75:$(Build.BuildId)'
