apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-demo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-container1
        image: mycontainerregistryem.azurecr.io/egam1/demo
        ports:
        -  containerPort: 80
